name: calcula_fuel
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.2
  cupertino_icons: ^1.0.8
  google_mobile_ads: ^5.1.0
  supabase_flutter: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/carfuel.png
    - assets/promo_placeholder.png # New asset
